package com.tl.invest.user.msg;

// Generated Nov 17, 2014 3:11:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserMsg generated by hbm2java
 */
public class UserMsg {

	private int id;
	private Integer msgFromId;
	private String msgFrom;
	private Integer msgToId;
	private String msgTo;
	private String msgContent;
	private Integer msgIsRead;
	private Date createTime;

	public UserMsg() {
	}

	public UserMsg(int id) {
		this.id = id;
	}

	public UserMsg(int id, Integer msgFromId, String msgFrom, Integer msgToId,
			String msgTo, String msgContent, Integer msgIsRead, Date createTime) {
		this.id = id;
		this.msgFromId = msgFromId;
		this.msgFrom = msgFrom;
		this.msgToId = msgToId;
		this.msgTo = msgTo;
		this.msgContent = msgContent;
		this.msgIsRead = msgIsRead;
		this.createTime = createTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getMsgFromId() {
		return this.msgFromId;
	}

	public void setMsgFromId(Integer msgFromId) {
		this.msgFromId = msgFromId;
	}

	public String getMsgFrom() {
		return this.msgFrom;
	}

	public void setMsgFrom(String msgFrom) {
		this.msgFrom = msgFrom;
	}

	public Integer getMsgToId() {
		return this.msgToId;
	}

	public void setMsgToId(Integer msgToId) {
		this.msgToId = msgToId;
	}

	public String getMsgTo() {
		return this.msgTo;
	}

	public void setMsgTo(String msgTo) {
		this.msgTo = msgTo;
	}

	public String getMsgContent() {
		return this.msgContent;
	}

	public void setMsgContent(String msgContent) {
		this.msgContent = msgContent;
	}

	public Integer getMsgIsRead() {
		return this.msgIsRead;
	}

	public void setMsgIsRead(Integer msgIsRead) {
		this.msgIsRead = msgIsRead;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
