<li style="height: 46px;line-height: 46px;margin-bottom: 3px;">
	<a href="../help/RegDoc.do" style="display: block;font-size: 14px;color: #333;font-weight: bold;padding: 0 10px 0 34px;height: 100%;">
		用户注册服务协议
	</a>
</li>
<li style="height: 46px;line-height: 46px;margin-bottom: 3px;">
	<a href="../help/Agreement.do" style="display: block;font-size: 14px;color: #333;font-weight: bold;padding: 0 10px 0 34px;height: 100%;">
		项目服务协议
	</a>
</li>