package com.tl.invest.recruit;

// Generated Nov 14, 2014 3:49:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Recruit generated by hbm2java
 */
public class Recruit {

	private int id;
	private Integer userId;
	private String userName;
	private String jobName;
	private String company;
	private String linkman;
	private String linkPhone;
	private String linkEmail;
	private String province;
	private String city;
	private String area;
	private String address;
	private String companyNature;
	private String salary;
	private String location;
	private String trade;
	private String scale;
	private String content;
	private String homePage;
	private String working;
	private String eduReq;
	private Integer isFulltime;
	private String jobAttract;
	private String jobIntro;
	private Date createtime;
	private Date pubTime;
	private Integer isPub;

	public Recruit() {
	}

	public Recruit(int id, Date createtime, Date pubTime) {
		this.id = id;
		this.createtime = createtime;
		this.pubTime = pubTime;
	}

	public Recruit(int id, Integer userId, String userName, String jobName,
			String company, String linkman, String linkPhone, String linkEmail,
			String province, String city, String area, String address,
			String companyNature, String salary, String location, String trade,
			String scale, String content, String homePage, String working,
			String eduReq, Integer isFulltime, String jobAttract,
			String jobIntro, Date createtime, Date pubTime, Integer isPub) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.jobName = jobName;
		this.company = company;
		this.linkman = linkman;
		this.linkPhone = linkPhone;
		this.linkEmail = linkEmail;
		this.province = province;
		this.city = city;
		this.area = area;
		this.address = address;
		this.companyNature = companyNature;
		this.salary = salary;
		this.location = location;
		this.trade = trade;
		this.scale = scale;
		this.content = content;
		this.homePage = homePage;
		this.working = working;
		this.eduReq = eduReq;
		this.isFulltime = isFulltime;
		this.jobAttract = jobAttract;
		this.jobIntro = jobIntro;
		this.createtime = createtime;
		this.pubTime = pubTime;
		this.isPub = isPub;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinkPhone() {
		return this.linkPhone;
	}

	public void setLinkPhone(String linkPhone) {
		this.linkPhone = linkPhone;
	}

	public String getLinkEmail() {
		return this.linkEmail;
	}

	public void setLinkEmail(String linkEmail) {
		this.linkEmail = linkEmail;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCompanyNature() {
		return this.companyNature;
	}

	public void setCompanyNature(String companyNature) {
		this.companyNature = companyNature;
	}

	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getTrade() {
		return this.trade;
	}

	public void setTrade(String trade) {
		this.trade = trade;
	}

	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getHomePage() {
		return this.homePage;
	}

	public void setHomePage(String homePage) {
		this.homePage = homePage;
	}

	public String getWorking() {
		return this.working;
	}

	public void setWorking(String working) {
		this.working = working;
	}

	public String getEduReq() {
		return this.eduReq;
	}

	public void setEduReq(String eduReq) {
		this.eduReq = eduReq;
	}

	public Integer getIsFulltime() {
		return this.isFulltime;
	}

	public void setIsFulltime(Integer isFulltime) {
		this.isFulltime = isFulltime;
	}

	public String getJobAttract() {
		return this.jobAttract;
	}

	public void setJobAttract(String jobAttract) {
		this.jobAttract = jobAttract;
	}

	public String getJobIntro() {
		return this.jobIntro;
	}

	public void setJobIntro(String jobIntro) {
		this.jobIntro = jobIntro;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getPubTime() {
		return this.pubTime;
	}

	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	public Integer getIsPub() {
		return this.isPub;
	}

	public void setIsPub(Integer isPub) {
		this.isPub = isPub;
	}

}
