package com.tl.sys.user;

// Generated Aug 27, 2014 10:19:08 AM by Hibernate Tools 3.4.0.CR1

/**
 * Photogroup generated by hbm2java
 */
public class Photogroup implements java.io.Serializable {

	private int id;
	private String groupName;

	public Photogroup() {
	}

	public Photogroup(int id) {
		this.id = id;
	}

	public Photogroup(int id, String groupName) {
		this.id = id;
		this.groupName = groupName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
