package com.tl.sys.user;

// Generated Aug 27, 2014 10:19:08 AM by Hibernate Tools 3.4.0.CR1

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private int id;
	private String name;

	public Type() {
	}

	public Type(int id) {
		this.id = id;
	}

	public Type(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
