package com.tl.invest.proj;

// Generated 2014-9-9 23:05:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * InvestProjmode generated by hbm2java
 */
public class ProjMode implements java.io.Serializable {

	private static final long serialVersionUID = -2408835528986363770L;
	
	private long id;
	private long projId;	
	private String name;
	private BigDecimal price;
	private String imgURL;
	/*
	 * 目标数量
	 */
	private int countGoal;
	/*
	 * 回报
	 */
	private String returnContent;
	/*
	 * 回报发送时间
	 */
	private String returntime;
	/*
	 * 配送费用
	 */
	private BigDecimal freight;
	private int deleted;
	/*
	 * 1=众筹中;2=名额已满;0=暂停
	 */
	private int status;

	public ProjMode() {
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getProjId() {
		return projId;
	}

	public void setProjId(long projId) {
		this.projId = projId;
	}


	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	

	public int getCountGoal() {
		return countGoal;
	}

	public void setCountGoal(int countGoal) {
		this.countGoal = countGoal;
	}
	
	public String getImgURL() {
		return imgURL;
	}

	public void setImgURL(String imgURL) {
		this.imgURL = imgURL;
	}

	public String getReturnContent() {
		return returnContent;
	}

	public void setReturnContent(String returnContent) {
		this.returnContent = returnContent;
	}

	public String getReturntime() {
		return returntime;
	}

	public void setReturntime(String returntime) {
		this.returntime = returntime;
	}

	public BigDecimal getFreight() {
		return freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	public int getDeleted() {
		return deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
}
