package com.tl.invest.proj;

// Generated 2014-9-9 23:05:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.tl.common.DateUtils;

/**
 * InvestProjsupport generated by hbm2java
 */
public class ProjSupport implements java.io.Serializable {

	private static final long serialVersionUID = 7286196772641479724L;
	
	private long id;
	private long projId;
	private long modeId;
	private int userId;
	private int canpay; //是否可以支付，主要用于竞拍项目，后台可以设置谁可以支付，项目结束后可以支付
	private Date lastpaytime; //最后付款时间，默认为竞拍成功后48小时
	private String lastpaytimeStr;
	public String getLastpaytimeStr() {
		if(getLastpaytime()!=null){
			return DateUtils.format(getLastpaytime(), "yyyy-MM-dd HH:mm:ss");
		}
		return "";
		
	}

	private int delaycount;  //延时付款次数，可以延时一次48小时付款
	private BigDecimal amount;
	private Integer addressId;
	private String recipients;
	private String telphone;
	private String address;
	private String zipcode;
	private String message;
	private Date created;
	private int deleted;
	/**
	 * 0=未付款;1=已付款;2=已发货;3=已确认收货;4=交易关闭
	 */
	private int status;
	private int isPaid;
	private Long orderId;
	private String paySN;
	private Date payTime;
	private int isAnonymous;

	public ProjSupport() {
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getProjId() {
		return projId;
	}

	public void setProjId(long projId) {
		this.projId = projId;
	}

	public long getModeId() {
		return modeId;
	}

	public void setModeId(long modeId) {
		this.modeId = modeId;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	public int getCanpay() {
		return canpay;
	}

	public void setCanpay(int canpay) {
		this.canpay = canpay;
	}
	
	public Date getLastpaytime() {
		return lastpaytime;
	}

	public void setLastpaytime(Date lastpaytime) {
		this.lastpaytime = lastpaytime;
		getLastpaytimeStr();
	}

	public int getDelaycount() {
		return delaycount;
	}

	public void setDelaycount(int delaycount) {
		this.delaycount = delaycount;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Integer getAddressId() {
		return addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public int getDeleted() {
		return deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public String getPaySN() {
		return paySN;
	}

	public void setPaySN(String paySN) {
		this.paySN = paySN;
	}

	public Date getPayTime() {
		return payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	public int getIsPaid() {
		return isPaid;
	}

	public void setIsPaid(int isPaid) {
		this.isPaid = isPaid;
	}

	public String getRecipients() {
		return recipients;
	}

	public void setRecipients(String recipients) {
		this.recipients = recipients;
	}

	public String getTelphone() {
		return telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public int getIsAnonymous() {
		return isAnonymous;
	}

	public void setIsAnonymous(int isAnonymous) {
		this.isAnonymous = isAnonymous;
	}
}
