--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.858
--   Created On : 星期日, 24 八月, 2014 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;




--  Create Tables 
CREATE TABLE bankcard
(
	id INTEGER NOT NULL COMMENT 'id',
	userID INTEGER COMMENT '用户ID',
	userName VARCHAR(255) COMMENT '用户名称',
	bankName VARCHAR(255) COMMENT '所属银行',
	openingBank VARCHAR(255) COMMENT '银行卡开户行：实名认证时需要填写',
	bankNum VARCHAR(50) COMMENT '银行卡号：实名认证时需要填写',
	authCode VARCHAR(50) COMMENT '银行卡验证码：绑定银行卡时，网站往银行卡打几分钱，客户收到后，将几分钱数字做为验证码，进行绑定银行卡。',
	isBound INTEGER DEFAULT 0 COMMENT '是否绑定：1=绑定成功,0=为未绑定',
	createTime TIMESTAMP(0) COMMENT '创建时间',
	PRIMARY KEY (id)
)  COMMENT='银行卡'
;


CREATE TABLE photogroup
(
	id INTEGER NOT NULL COMMENT 'id',
	groupName VARCHAR(255) COMMENT '组图名称',
	PRIMARY KEY (id)
) 
;


CREATE TABLE type
(
	id INTEGER NOT NULL COMMENT 'id',
	name VARCHAR(255) COMMENT '名称',
	PRIMARY KEY (id)
)  COMMENT='个人＼团队＼机构'
;


CREATE TABLE user
(
	id INTEGER NOT NULL COMMENT 'ID',
	code VARCHAR(255) COMMENT '登录账号:第三方认证的使用第三方的账号，但需要完善其他必填字段',
	password VARCHAR(255) COMMENT '密码：（第三方认证不需要）',
	name VARCHAR(255) COMMENT '姓名：实名认证时必须',
	type_id INTEGER COMMENT '注册类型：0-个人、1-团队、2-机构',
	type VARCHAR(255) COMMENT '注册类型：0-个人、1-团队、2-机构',
	city VARCHAR(255) COMMENT '地域：省-市',
	head VARCHAR(255) COMMENT '头像',
	intro TEXT COMMENT '简介：个人介绍、团队成员介绍、机构介绍',
	wechat VARCHAR(255) COMMENT '微信',
	microblog VARCHAR(255) COMMENT '微博',
	nickName VARCHAR(255) COMMENT '昵称',
	job VARCHAR(255) COMMENT '职业',
	email VARCHAR(255) COMMENT '邮箱：为了找回密码使用',
	phone VARCHAR(255) COMMENT '手机：实名认证时需要填写',
	identityCard NVARCHAR(255) COMMENT '身份证-实名认证时需要填写',
	organization VARCHAR(255) COMMENT '企业组织机构证件照：企业实名认证时需要填写',
	businessLicense VARCHAR(255) COMMENT '企业营业执照扫描件：企业实名认证时需要填写',
	isRealNameIdent INTEGER COMMENT '是否已经实名认证：1=认证，2=未认证',
	createTime TIMESTAMP(0) COMMENT '创建时间',
	PRIMARY KEY (id)
)  COMMENT='用户表'
;


CREATE TABLE userphoto
(
	id INTEGER NOT NULL COMMENT 'id',
	userID INTEGER COMMENT '用户ID',
	userName NVARCHAR(255) COMMENT '用户名称',
	groupID INTEGER COMMENT '图册组ID',
	groupName VARCHAR(255) COMMENT '图册组名称',
	photo VARCHAR(500) COMMENT '图片',
	note TEXT COMMENT '详述',
	createTime TIMESTAMP(0) COMMENT '创建时间',
	PRIMARY KEY (id)
) 
;


CREATE TABLE works
(
	id INTEGER NOT NULL COMMENT 'id',
	userID INTEGER COMMENT '用户ID',
	userName VARCHAR(255) COMMENT '用户名称',
	name VARCHAR(255) COMMENT '作品名称',
	content TEXT COMMENT '作品：可以多个作品(文字、图片、视频)',
	createTime TIMESTAMP(0) COMMENT '创建时间',
	worksTime TIMESTAMP(0) COMMENT '作品时间',
	PRIMARY KEY (id)
) 
;



SET FOREIGN_KEY_CHECKS=1;
