--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.858
--   Created On : ÐÇÆÚÈÕ, 24 °ËÔÂ, 2014 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;




--  Create Tables 
CREATE TABLE sysuser
(
	id INTEGER NOT NULL DEFAULT 50,
	username VARCHAR(255),
	code VARCHAR(255),
	pwd VARCHAR(255),
	createTime TIMESTAMP(0),
	PRIMARY KEY (id)
) 
;



SET FOREIGN_KEY_CHECKS=1;
