package com.tl.invest.user;

// Generated Aug 27, 2014 10:19:08 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 300302988599220144L;
	private int id;
	private String code;
	private String password;
	private String name;
	private Integer typeId;
	private String type;
	private String province;
	private String city;
	private String head;
	private String intro;
	private String wechat;
	private String microblog;
	private String nickName;
	private String job;
	private String email;
	private String phone;
	private String identityCard;
	private String organization;
	private String businessLicense;
	private Integer isRealNameIdent;
	private Date createTime;
	private String createTimeStr;
	private String postAddr;
	private List<Bankcard> bankcards;

	public User() {
	}

	public User(int id, Date createTime) {
		this.id = id;
		this.createTime = createTime;
	}

	public User(int id, String code, String password, String name,
			Integer typeId, String type, String city, String head,
			String intro, String wechat, String microblog, String nickName,
			String job, String email, String phone, String identityCard,
			String organization, String businessLicense,
			Integer isRealNameIdent, Date createTime) {
		this.id = id;
		this.code = code;
		this.password = password;
		this.name = name;
		this.typeId = typeId;
		this.type = type;
		this.city = city;
		this.head = head;
		this.intro = intro;
		this.wechat = wechat;
		this.microblog = microblog;
		this.nickName = nickName;
		this.job = job;
		this.email = email;
		this.phone = phone;
		this.identityCard = identityCard;
		this.organization = organization;
		this.businessLicense = businessLicense;
		this.isRealNameIdent = isRealNameIdent;
		this.createTime = createTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public String getWechat() {
		return this.wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	public String getMicroblog() {
		return this.microblog;
	}

	public void setMicroblog(String microblog) {
		this.microblog = microblog;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public String getBusinessLicense() {
		return this.businessLicense;
	}

	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense;
	}

	public Integer getIsRealNameIdent() {
		return this.isRealNameIdent;
	}

	public void setIsRealNameIdent(Integer isRealNameIdent) {
		this.isRealNameIdent = isRealNameIdent;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateTimeStr() {
		return createTimeStr;
	}

	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}
	public String getPostAddr() {
		return postAddr;
	}

	public void setPostAddr(String postAddr) {
		this.postAddr = postAddr;
	}

	public List<Bankcard> getBankcards() {
		return bankcards;
	}

	public void setBankcards(List<Bankcard> bankcards) {
		this.bankcards = bankcards;
	}
}