package com.tl.invest.user;

// Generated Aug 27, 2014 10:19:08 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Userphoto generated by hbm2java
 */
public class Userphoto {

	private int id;
	private Integer userId;
	private String userName;
	private Integer groupId;
	private String groupName;
	private String photo;
	private String note;
	private Date createTime;

	public Userphoto() {
	}

	public Userphoto(int id, Date createTime) {
		this.id = id;
		this.createTime = createTime;
	}

	public Userphoto(int id, Integer userId, String userName, Integer groupId,
			String groupName, String photo, String note, Date createTime) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.groupId = groupId;
		this.groupName = groupName;
		this.photo = photo;
		this.note = note;
		this.createTime = createTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
