package com.tl.invest.user;

// Generated Aug 27, 2014 10:19:08 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Works generated by hbm2java
 */
public class Works {

	private int id;
	private Integer userId;
	private String userName;
	private String name;
	private String content;
	private Date createTime;
	private Date worksTime;

	public Works() {
	}

	public Works(int id, Date createTime, Date worksTime) {
		this.id = id;
		this.createTime = createTime;
		this.worksTime = worksTime;
	}

	public Works(int id, Integer userId, String userName, String name,
			String content, Date createTime, Date worksTime) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.name = name;
		this.content = content;
		this.createTime = createTime;
		this.worksTime = worksTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getWorksTime() {
		return this.worksTime;
	}

	public void setWorksTime(Date worksTime) {
		this.worksTime = worksTime;
	}

}
