<br/>
<div class="footer">
	<div class="wrap">
		<div class="info hidden-xs">
			<ul>
				<li><h2>发起项目</h2></li>
				<li><a href="<c:out value="${rootPath}"/>project/Publish.do?type=0">微电影</a></li>
				<li><a href="<c:out value="${rootPath}"/>project/Publish.do?type=1">电影长片</a></li>
				<li><a href="<c:out value="${rootPath}"/>project/Publish.do?type=2">电影相关</a></li>
			</ul>
			<ul>
				<li><h2>发起影聘</h2></li>
				<li><a href="<c:out value="${rootPath}"/>recruit/Edit.do?a=detail&mainType=3">前期拍摄</a></li>
				<li><a href="<c:out value="${rootPath}"/>recruit/Edit.do?a=detail&mainType=3">后期制作</a></li>
				<li><a href="<c:out value="${rootPath}"/>recruit/Edit.do?a=detail&mainType=3">宣传发行</a></li>
				<li><a href="<c:out value="${rootPath}"/>recruit/Edit.do?a=detail&mainType=3">动画片制作</a></li>
			</ul>
			<ul>
				<li><h2>关于我们</h2></li>
				<li><a href="#">何为合众映画</a></li>
				<li><a href="#">联系我们</a></li>
				<li><a href="#">帮助中心</a></li>
				<li><a href="#">服务协议</a></li>
			</ul>
			<ul>
				<li><h2>商务合作</h2></li>
				<li>邮箱：<br />server@yingxiang.com<br />客服热线：<br />400-888-8888</li>
			</ul>
			<ul class="last">
				<li><h2>关注我们</h2></li>
				<li class="ewm">
					<img src="<c:out value="${rootPath}"/>static/image/ewm.png" />
					<span>扫描二维码<br />关注更多</span>
				</li>
				<li class="share">
					<span class="s1"><a href="#">新浪微博</a></span>
					<span class="s2"><a href="#">微信</a></span>
				</li>
			</ul>
		</div>
	</div>
	<div class="copyright">
		©2014 北京合众映画影视科技有限公司 www.hzcine.com 版权所有
		京ICP备15000396号　<!--京公网安备110105015888-->
	</div>
	<div id="sharedialog" style="display:none;">
        <div class="bdsharebuttonbox" data-tag="share_1">
            <a class="bds_qzone" data-cmd="qzone" href="#"></a>
            <a class="bds_tsina" data-cmd="tsina"></a>
            <a class="bds_weixin" data-cmd="weixin"></a>
            <a class="bds_renren" data-cmd="renren"></a>
            <a class="bds_tqq" data-cmd="tqq"></a>
        </div>
    </div>
	<script type="text/javascript">
		 
		 window._bd_share_config = {
            common: {
				bdMini:"2",
				bdMiniList:["tsina","qzone","weixin","renren","tqq","douban"],
                bdText: '',
                bdDesc: '',
                bdUrl: '',
                bdPic: ''
            },
            share: [{
                "bdSize": 16
            }] 
        };
	with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?cdnversion='+~(-new Date()/36e5)];
	 $(".pic img").zoom({height:160,width:232});
	 
	
	
	</script>
</div>