<div class="footer">
	<div class="wrap">
		<div class="info">
			<ul>
				<li><h2>发起项目</h2></li>
				<li><a href="#">微电影</a></li>
				<li><a href="#">电影长片</a></li>
				<li><a href="#">电影相关</a></li>
			</ul>
			<ul>
				<li><h2>发起影聘</h2></li>
				<li><a href="#">前期拍摄</a></li>
				<li><a href="#">后期制作</a></li>
				<li><a href="#">宣传发行</a></li>
				<li><a href="#">动画电影</a></li>
			</ul>
			<ul>
				<li><h2>关于我们</h2></li>
				<li><a href="#">何为合众映画</a></li>
				<li><a href="#">联系我们</a></li>
				<li><a href="#">帮助中心</a></li>
				<li><a href="#">服务协议</a></li>
			</ul>
			<ul>
				<li><h2>商务合作</h2></li>
				<li>邮箱：<br />server@yingxiang.com<br />客服热线：<br />400-888-8888</li>
			</ul>
			<ul class="last">
				<li><h2>关注我们</h2></li>
				<li class="ewm">
					<img src="../static/image/ewm.png" />
					<span>扫描二维码<br />关注更多</span>
				</li>
				<li class="share">
					<span class="s1"><a href="#">新浪微博</a></span>
					<span class="s2"><a href="#">微信</a></span>
				</li>
			</ul>
		</div>
	</div>
	<div class="copyright">
		©2014 北京合众映画影视科技有限公司 Hezhongfilm.com 版权所有<br />
		京ICP备140118851号　京公网安备110105015888
	</div>
</div>