<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><c:out value="${title}"/></title>
<meta name="keywords" content="<c:out value="${keywords}"/>" />
<meta name="description" content="<c:out value="${description}"/>" />
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<!-- Basic Styles -->

<link rel="stylesheet" type="text/css" media="screen" href="<c:out value="${rootPath}"/>js/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="<c:out value="${rootPath}"/>static/css/reset.css" />
<link rel="stylesheet" type="text/css" href="<c:out value="${rootPath}"/>static/css/index.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<c:out value="${rootPath}"/>/js/plugin/artdialog/css/ui-dialog.css">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

<script type="text/javascript" src="<c:out value="${rootPath}"/>js/jquery/jquery.min.js"></script>
<script type="text/javascript" src="<c:out value="${rootPath}"/>js/jquery/jquery-migrate.min.js"></script>
<script type="text/javascript" src="<c:out value="${rootPath}"/>js/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<c:out value="${rootPath}"/>static/js/common.js"></script>
<script type="text/javascript" src="<c:out value="${rootPath}"/>js/utils.js"></script>
<script type="text/javascript" src="<c:out value="${rootPath}"/>js/plugin/jquery.bootstrap.dialog-plus/jquery.dialog-plus.js"></script>