<!-- FAVICONS -->
<link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
<link rel="icon" href="../favicon.ico" type="image/x-icon">
<!-- validation Styles -->
<link rel="stylesheet" type="text/css" href="../js/bootstrap/css/bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="../js/plugin/jquery-validate/css/validationEngine.jquery.css"/>
<!-- invest Styles -->

<link rel="stylesheet" type="text/css" href="../static/css/reset.css" />
<link rel="stylesheet" type="text/css" href="../static/css/index.css" />
<link rel="stylesheet" type="text/css" href="../user/css/userCenter.css" />
<link rel="stylesheet" type="text/css" media="screen" href="../js/plugin/artdialog/css/ui-dialog.css">

