<!-- FAVICONS -->
<link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
<link rel="icon" href="../favicon.ico" type="image/x-icon">
<!-- validation Styles -->
<link rel="stylesheet" type="text/css" href="../js/plugin/jquery-validate/css/validationEngine.jquery.css"/>
<!-- easyui Styles -->
<link rel="stylesheet" type="text/css" href="../js/jquery-easyui/themes/default/easyui.css"/>
<link rel="stylesheet" type="text/css" href="../js/jquery-easyui/themes/icon.css"/>
<!-- invest Styles -->
<link rel="stylesheet" type="text/css" href="../static/css/reset.css" />
<link rel="stylesheet" type="text/css" href="../static/css/index.css" />
<link rel="stylesheet" type="text/css" href="../user/css/userCenter.css" />