<!-- JARVIS QUERY -->
<script type="text/javascript" src="../js/jquery/jquery.min.js"></script>
<script type="text/javascript" src="../js/jquery/jquery-migrate.min.js"></script>
<script type="text/javascript" src="../js/plugin/query/jquery.query.js"></script>
<script type="text/javascript" src="../js/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../js/plugin/jquery-validate/js/jquery.validationEngine.js"></script>
<script type="text/javascript" src="../js/plugin/jquery-validate/js/languages/jquery.validationEngine-zh_CN.js"></script>
<script type="text/javascript" src="../js/utils.js"></script>
<script type="text/javascript" src="../static/js/common.js"></script>
<script type="text/javascript" src="../user/common/head.js"></script>
<script type="text/javascript" src="../js/plugin/artdialog/dist/dialog-plus.js"></script>
<script type="text/javascript" src="../js/plugin/jquery.bootstrap.dialog-plus/jquery.dialog-plus.js"></script>
<script type="text/javascript" src="../js/share.js"></script>
