package com.tl.sys.sysuser;

// Generated Aug 24, 2014 9:27:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.tl.common.DateUtils;

/**
 * Sysuser generated by hbm2java
 */
@SuppressWarnings({"serial", "unused"})
public class Sysuser implements java.io.Serializable {

	private int id;
	private String username;
	private String code;
	private String pwd;
	private Date createTime;
	private String createTimeStr;
	public Sysuser() {
	}

	public Sysuser(int id, Date createTime) {
		this.id = id;
		this.createTime = createTime;
	}
	public Sysuser(String username, String code, String pwd,
			Date createTime) {
		this.username = username;
		this.code = code;
		this.pwd = pwd;
		this.createTime = createTime;
	}
	
	public Sysuser(int id, String username, String code, String pwd,
			Date createTime) {
		this.id = id;
		this.username = username;
		this.code = code;
		this.pwd = pwd;
		this.createTime = createTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Date getCreateTime() {
		return this.createTime;
	}
	
	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}

	public String getCreateTimeStr() {
		return DateUtils.format(this.createTime, "yyyy-MM-dd HH:mm:ss");
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
