package com.tl.invest.user.resume;

// Generated Nov 17, 2014 3:11:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserResume generated by hbm2java
 */
public class UserResume {

	private int id;
	private Integer userId;
	private String userName;
	private String name;
	private String affix;
	private String content;
	private int height;
	private int weight;
	private String school;
	private String professional;
	public String getProfessional() {
		return professional;
	}

	public void setProfessional(String professional) {
		this.professional = professional;
	}

	private int degreeid;
	private String degree;
	public int getHeight() {
		return height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public int getWeight() {
		return weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public String getSchool() {
		return school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public int getDegreeid() {
		return degreeid;
	}

	public void setDegreeid(int degreeid) {
		this.degreeid = degreeid;
	}

	public String getDegree() {
		return degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	private Date createTime;

	public UserResume() {
	}

	public UserResume(int id) {
		this.id = id;
	}

	public UserResume(int id, Integer userId, String userName, String name,
			String affix, String content, Date createTime) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.name = name;
		this.affix = affix;
		this.content = content;
		this.createTime = createTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAffix() {
		return this.affix;
	}

	public void setAffix(String affix) {
		this.affix = affix;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
