package com.tl.invest.user.video;

// Generated Nov 17, 2014 3:11:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserVideogroup generated by hbm2java
 */
public class UserVideogroup {

	private int id;
	private Integer userId;
	private String userName;
	private String videoName;
	private String videoIntro;

	public UserVideogroup() {
	}

	public UserVideogroup(int id) {
		this.id = id;
	}

	public UserVideogroup(int id, Integer userId, String userName,
			String videoName, String videoIntro) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.videoName = videoName;
		this.videoIntro = videoIntro;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getVideoName() {
		return this.videoName;
	}

	public void setVideoName(String videoName) {
		this.videoName = videoName;
	}

	public String getVideoIntro() {
		return this.videoIntro;
	}

	public void setVideoIntro(String videoIntro) {
		this.videoIntro = videoIntro;
	}

}
