package com.tl.invest.user.user;

// Generated Nov 17, 2014 3:11:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import com.tl.invest.user.bankcard.UserBankcard;

/**
 * User generated by hbm2java
 */
public class User {

	private int id;
	private Integer type;
	private String code;
	private String email;
	private String password;
	private String name;
	private String identityCard;
	private String head;
	private String intro;
	private String background;
	private Integer isRealNameIdent;
	private Date createTime;
	private String qqOpenId;
	private String xlWeiboCode;
	private String perNickName;
	private String perPostAddr;
	private String perPostCode;
	private String perProvince;
	private String perCity;
	private String perJob;
	private String perPhone;
	private String orgShortname;
	private String orgFullname;
	private String organization;
	private String orgBusinessLicense;
	private String orgAddress;
	private String orgNature;
	private String orgTrade;
	private String orgScale;
	private String orgHomePage;
	private List<UserBankcard> bankcards;
	public User() {
	}

	public User(int id) {
		this.id = id;
	}

	public User(int id, Integer type, String code, String email,
			String password, String name, String identityCard, String head,
			String intro, String background, Integer isRealNameIdent,
			Date createTime, String qqOpenId, String xlWeiboCode,
			String perNickName, String perPostAddr, String perPostCode,
			String perProvince, String perCity, String perJob, String perPhone,
			String orgShortname, String orgFullname, String organization,
			String orgBusinessLicense, String orgAddress, String orgNature,
			String orgTrade, String orgScale, String orgHomePage) {
		this.id = id;
		this.type = type;
		this.code = code;
		this.email = email;
		this.password = password;
		this.name = name;
		this.identityCard = identityCard;
		this.head = head;
		this.intro = intro;
		this.background = background;
		this.isRealNameIdent = isRealNameIdent;
		this.createTime = createTime;
		this.qqOpenId = qqOpenId;
		this.xlWeiboCode = xlWeiboCode;
		this.perNickName = perNickName;
		this.perPostAddr = perPostAddr;
		this.perPostCode = perPostCode;
		this.perProvince = perProvince;
		this.perCity = perCity;
		this.perJob = perJob;
		this.perPhone = perPhone;
		this.orgShortname = orgShortname;
		this.orgFullname = orgFullname;
		this.organization = organization;
		this.orgBusinessLicense = orgBusinessLicense;
		this.orgAddress = orgAddress;
		this.orgNature = orgNature;
		this.orgTrade = orgTrade;
		this.orgScale = orgScale;
		this.orgHomePage = orgHomePage;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public String getBackground() {
		return this.background;
	}

	public void setBackground(String background) {
		this.background = background;
	}

	public Integer getIsRealNameIdent() {
		return this.isRealNameIdent;
	}

	public void setIsRealNameIdent(Integer isRealNameIdent) {
		this.isRealNameIdent = isRealNameIdent;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getQqOpenId() {
		return this.qqOpenId;
	}

	public void setQqOpenId(String qqOpenId) {
		this.qqOpenId = qqOpenId;
	}

	public String getXlWeiboCode() {
		return this.xlWeiboCode;
	}

	public void setXlWeiboCode(String xlWeiboCode) {
		this.xlWeiboCode = xlWeiboCode;
	}

	public String getPerNickName() {
		return this.perNickName;
	}

	public void setPerNickName(String perNickName) {
		this.perNickName = perNickName;
	}

	public String getPerPostAddr() {
		return this.perPostAddr;
	}

	public void setPerPostAddr(String perPostAddr) {
		this.perPostAddr = perPostAddr;
	}

	public String getPerPostCode() {
		return this.perPostCode;
	}

	public void setPerPostCode(String perPostCode) {
		this.perPostCode = perPostCode;
	}

	public String getPerProvince() {
		return this.perProvince;
	}

	public void setPerProvince(String perProvince) {
		this.perProvince = perProvince;
	}

	public String getPerCity() {
		return this.perCity;
	}

	public void setPerCity(String perCity) {
		this.perCity = perCity;
	}

	public String getPerJob() {
		return this.perJob;
	}

	public void setPerJob(String perJob) {
		this.perJob = perJob;
	}

	public String getPerPhone() {
		return this.perPhone;
	}

	public void setPerPhone(String perPhone) {
		this.perPhone = perPhone;
	}

	public String getOrgShortname() {
		return this.orgShortname;
	}

	public void setOrgShortname(String orgShortname) {
		this.orgShortname = orgShortname;
	}

	public String getOrgFullname() {
		return this.orgFullname;
	}

	public void setOrgFullname(String orgFullname) {
		this.orgFullname = orgFullname;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public String getOrgBusinessLicense() {
		return this.orgBusinessLicense;
	}

	public void setOrgBusinessLicense(String orgBusinessLicense) {
		this.orgBusinessLicense = orgBusinessLicense;
	}

	public String getOrgAddress() {
		return this.orgAddress;
	}

	public void setOrgAddress(String orgAddress) {
		this.orgAddress = orgAddress;
	}

	public String getOrgNature() {
		return this.orgNature;
	}

	public void setOrgNature(String orgNature) {
		this.orgNature = orgNature;
	}

	public String getOrgTrade() {
		return this.orgTrade;
	}

	public void setOrgTrade(String orgTrade) {
		this.orgTrade = orgTrade;
	}

	public String getOrgScale() {
		return this.orgScale;
	}

	public void setOrgScale(String orgScale) {
		this.orgScale = orgScale;
	}

	public String getOrgHomePage() {
		return this.orgHomePage;
	}

	public void setOrgHomePage(String orgHomePage) {
		this.orgHomePage = orgHomePage;
	}

	public List<UserBankcard> getBankcards() {
		return bankcards;
	}

	public void setBankcards(List<UserBankcard> bankcards) {
		this.bankcards = bankcards;
	}
}