<!-- Basic Styles -->
<link rel="stylesheet" type="text/css" media="screen" href="../js/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="screen" href="../css/font-awesome.min.css">

<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
<link rel="stylesheet" type="text/css" media="screen" href="../css/smartadmin-production.css">
<link rel="stylesheet" type="text/css" media="screen" href="../css/smartadmin-skins.css">

<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
<link rel="stylesheet" type="text/css" media="screen" href="../css/skinset.css">

<!-- FAVICONS -->
<link rel="shortcut icon" href="../img/favicon/favicon.ico" type="image/x-icon">
<link rel="icon" href="../img/favicon/favicon.ico" type="image/x-icon">