<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
<script data-pace-options='{ "restartOnRequestAfter": true }' src="../js/plugin/pace/pace.min.js"></script>

<script src="../js/jquery/jquery.min.js"></script>
		 
<script src="../js/jquery/jquery-ui.min.js"></script>

<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
<script src="js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

<!-- BOOTSTRAP JS -->
<script src="../js/bootstrap/js/bootstrap.min.js"></script>

<!-- JARVIS WIDGETS -->
<script src="../js/plugin/smartwidgets/jarvis.widget.min.js"></script>

<!-- JARVIS QUERY -->
<script src="../js/plugin/query/jquery.query.js"></script>

<!-- pub/sub -->
<script src="../js/plugin/jquery-tiny-pubsub/tiny-pubsub.js"></script>
