package com.tl.invest.user.bankcard;

import java.util.Date;

/**
 * UserBankcard generated by hbm2java
 */
public class UserBankcard {

	private int id;
	private Integer userId;
	private String userName;
	private String bankName;
	private String openingBank;
	private String bankNum;
	private String authCode;
	private Integer isBound;
	private Date createTime;

	public UserBankcard() {
	}

	public UserBankcard(int id, Date createTime) {
		this.id = id;
		this.createTime = createTime;
	}

	public UserBankcard(int id, Integer userId, String userName,
			String bankName, String openingBank, String bankNum,
			String authCode, Integer isBound, Date createTime) {
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.bankName = bankName;
		this.openingBank = openingBank;
		this.bankNum = bankNum;
		this.authCode = authCode;
		this.isBound = isBound;
		this.createTime = createTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getOpeningBank() {
		return this.openingBank;
	}

	public void setOpeningBank(String openingBank) {
		this.openingBank = openingBank;
	}

	public String getBankNum() {
		return this.bankNum;
	}

	public void setBankNum(String bankNum) {
		this.bankNum = bankNum;
	}

	public String getAuthCode() {
		return this.authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	public Integer getIsBound() {
		return this.isBound;
	}

	public void setIsBound(Integer isBound) {
		this.isBound = isBound;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
